---
sidebar: sidebar 
permalink: concept-cvs-gcp.html 
keywords: cloud volumes service for gcp, google cloud, cloud volumes, cloud volumes service subscription 
summary: 借助适用于 Google Cloud 的 NetApp Cloud Volumes Service ，您可以快速添加多协议工作负载，以及构建和部署基于 Windows 和基于 UNIX 的应用程序。 
---
= 了解适用于 Google Cloud 的 Cloud Volumes Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
借助适用于 Google Cloud 的 NetApp Cloud Volumes Service ，您可以快速添加多协议工作负载，以及构建和部署基于 Windows 和基于 UNIX 的应用程序。



== 主要功能：

* 在内部部署和 Google Cloud 之间迁移数据。
* 只需几秒钟即可配置 1 到 100 TiB 的卷。
* 多协议支持（您可以创建 NFS 或 SMB 卷）。
* 利用高效的自动化快照保护数据。
* 通过快速克隆加快应用程序开发速度。




== 成本

Cloud Volumes Service for Google Cloud创建的卷将计入您的服务订阅、而不是通过BlueXP进行收费。

从BlueXP中发现适用于Google Cloud的Cloud Volumes Service 区域或卷不收取任何费用。

link:https://console.cloud.google.com/marketplace/product/endpoints/cloudvolumesgcp-api.netapp.com?q=cloud%20volumes%20service["在 Google Cloud Marketplace 中查看定价"^]



== 支持的区域

https://cloud.netapp.com/cloud-volumes-global-regions#cvsGc["查看支持的 Google Cloud 区域"^]



== 开始之前

BlueXP可以发现现有Cloud Volumes Service for Google Cloud订阅和卷。请参见 https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud 文档"^] 如果您尚未设置订阅。



== 获取帮助

有关BlueXP中Cloud Volumes Service 操作的一般问题、请使用BlueXP聊天工具。

有关适用于 Google Cloud 的 Cloud Volumes Service 的一般问题，请发送电子邮件至 NetApp 的 Google Cloud 团队： gcinfo@netapp.com 。

对于与云卷相关的技术问题，您可以从 Google Cloud Console 创建技术支持案例。请参见 link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/support["获取支持"^] 了解详细信息。



== 相关链接

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp BlueXP：适用于Google Cloud的Cloud Volumes Service"^]
* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/["NetApp Cloud Volumes Service for Google Cloud 文档"^]

